spring.application.name=volgacoin

spring.datasource.url=jdbc:postgresql://localhost:5432/volgacoin
spring.datasource.username=volgacoin_user
spring.datasource.password=123456

telegram.bot.token=dsfsdfsdf